export function useServices() {
  return [
    {
      id: 1,
      title: 'NIGHT ON THE TOWN',
      subHeading: 'ENJOY YOURSELF',
      description: `Whether it is a birthday, bachelor party, bachelorette party or any other special occasion, we offer transportation for all of these occasions and more. Our drivers have experience catering to those who are celebrating milestones in their lives. Not only will they go out of their way to make sure you have a great time, but they will also help to ensure that you are safe too!`,
      excerpt: `We are a VIP Toronto car service offering professional service at a reasonable price. It's perfect for special occasions with friends and family. If you're looking to celebrate with your partner, our car service can get you where you need to go hassle-free and in comfort in an SUV or car. Our car service ensures you arrive safely and stylishly so that you can relax and enjoy your night out.`,
      icon: '',
      image: '',
      altText: 'Night-On-The-Town',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
    {
      id: 2,
      title: 'INTERCITY TRAVEL',
      subHeading: 'Avoid The Hassle',
      description: `In the current times of Covid-19, more business clients want to take a car service when they are going out of Toronto for a business trip. Having personal transportation when travelling from city to city in Southern Ontario can benefit you and your business. Whether travelling from Toronto to Ottawa or Toronto to Windsor, hire one of our reliable chauffeurs to take you from point A to point B.`,
      excerpt: '',
      icon: '',
      image: '',
      altText: 'Intercity-Travel',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },

    {
      id: 3,
      title: 'TORONTO INTERNATIONAL FILM FESTIVAL',
      subHeading: '',
      description: `Make the red carpet your runway with our Toronto car service and arrive at the largest film festival in Canada looking like a movie star. Travel to TIFF events in style and come feeling like a celebrity. There are many Toronto car services, but only one car service ensures you have a good time.`,
      excerpt:
        'Make the red carpet your runway with our Toronto car service and arrive at the largest film festival in Canada looking like a movie star. Travel to TIFF events in style and come feeling like a celebrity. There are many Toronto car services, but only one car service ensures you have a good time.',
      icon: '',
      image: '',
      altText: 'TIFF',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
    {
      id: 4,
      title: 'AIRPORT SERVICES',
      subHeading: 'Travel In Comfort',
      description: `No one wants to spend hours in an airport before their flight, but it is inevitable. With a limousine service, you do not need to worry about the time spent at the airport. Drivers are available 24/7 and can pick you up at any terminal. They will also drop you off at your terminal for your departure flight. When flying internationally, the process can be even more daunting with all of the security checks and hours of waiting in line. You will not have to worry about this as long as you are booked with a High Park Livery!`,
      excerpt: `Take your time. All travellers picked at Toronto Pearson International Airport get 60 minutes complimentary waiting time. For airport pickups, drivers track flights status tracking to ensure they are there when they arrive. We will load your luggage and take you to your hotel. We cover all airports in southern Ontario at reasonable prices.`,
      icon: '',
      image: '',
      altText: 'airport-services',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
    {
      id: 5,
      title: 'CORPORATE TRAVEL',
      subHeading: 'Dont Worry About Meetings',
      description: `With our car service, as far as we're concerned, you are number one! Arrive on time to all corporate events during your stay in Toronto. Whether you're coming in from Toronto Pearson Airport (YYZ) or from Toronto Airport (YTZ) located downtown Toronto we have a car or an SUV that will cover your needs.`,
      excerpt: '',
      icon: '',
      image: '',
      altText: 'Corporate-Travel',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
    {
      id: 6,
      title: 'POINT TO POINT SERVICES',
      subHeading: 'Always Be On Time',
      description: `Point-To-Point transfers are an excellent choice for anyone who wants more convenience when it comes to transportation. Many people rely on our company for transportation, and we work hard to provide them with a solution that matches up with their needs at all times. We will take care of your needs and make sure that you are happy with what you get.`,
      excerpt: `Point-to-point transfers are an excellent choice for anyone who wants more convenience when it comes to transportation. Many people rely on our company, and we work hard to provide them with a solution that matches up with their needs at all times. We will take care of every one of your needs and make sure that you are happy with what you get.`,
      icon: '',
      image: '',
      altText: 'Point-To-Point',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
    {
      id: 7,
      title: 'Hourly Services',
      subHeading: 'Have The Driver Wait',
      description: `We offer hourly service with a minimum of two hours. Hourly car service is perfect for running errands, going to appointments, or even giving friends and family rides. Hourly service is also excellent for date nights and parties! Suppose you are unsure about what your transportation needs are. In that case, we offer packages that include everything you need to make it convenient.`,
      excerpt: `We offer hourly service with a minimum of two hours. Hourly car service is perfect for running errands, going to appointments, or even giving friends and family rides. Hourly service is also excellent for date nights and parties! Suppose you are unsure about what your transportation needs are. In that case, we offer packages that include everything you need to make it convenient.`,
      icon: '',
      image: '',
      altText: 'Point-To-Point',
      buttonText: 'contact us',
      buttonLink: '/reservations',
    },
  ]
}
